version: '3.5'

services:
  image:
    container_name: rinha-de-backend
    image: rinha-de-backend
    command: php bin/hyperf.php list
    build:
      context: .
      args:
        APP_STAGE: dev

  api1:
    container_name: rinha-de-backend-app1
    image: rinha-de-backend
    environment:
      DB_HOST: db
    volumes:
      - ./:/opt/www
    depends_on:
      - db
      - image

  api2:
    container_name: rinha-de-backend-app2
    image: rinha-de-backend
    environment:
      DB_HOST: db
    volumes:
      - ./:/opt/www
    depends_on:
      - db
      - image

  db:
    container_name: rinha-de-backend-db
    image: mysql:8.1
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - ./migrations.sql:/docker-entrypoint-initdb.d/migrations.sql
    ports:
      - 3306:3306

  nginx:
    image: nginx
    container_name: rinha-de-backend-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
    ports:
      - 9999:9999

networks:
  default:
    name: rinha-de-backend