version: '3.5'

services:
  api1: &api
    container_name: rinha-de-backend-app1
    image: rinha-de-backend
    build:
      context: .
      args:
        APP_STAGE: dev
    environment:
      DB_HOST: db
    volumes:
      - ./:/opt/www
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '0.5GB'

  api2:
    <<: *api
    container_name: rinha-de-backend-app2

  db:
    container_name: rinha-de-backend-db
    image: mysql:8.1
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - ./migrations.sql:/docker-entrypoint-initdb.d/migrations.sql
    ports:
      - 3306:3306
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: '1.5GB'

  nginx:
    image: nginx
    container_name: rinha-de-backend-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - 9999:9999
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '0.5GB'

networks:
  default:
    name: rinha-de-backend