version: '3'
services:
  db:
    container_name: rinha-de-backend-db
    image: mysql:8.1
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - ./migrations.sql:/docker-entrypoint-initdb.d/migrations.sql
    ports:
      - 3306:3306

  app:
    container_name: rinha-de-backend-app
    image: rinha-de-backend-app
    build:
      context: .
    environment:
      DB_HOST: db
    volumes:
      - ./:/opt/www
    ports:
      - 9501:9501

networks:
  default:
    name: rinha-de-backend
