name: CI
on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  dockerhub:
    runs-on: ubuntu-latest
    steps:
    - uses: docker/login-action@v2
      name: Login to Docker Hub
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: actions/checkout@v3
    - name: Build and push Docker image
      run: make
