name: CI
on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
    - uses: docker/login-action@v2
    - name: Login to Docker Hub
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Docker image
      run: make build

  push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Push Docker image
      run: make push
